### PR TITLE
Implement PostgreSQL ASP.Net Identity Provider.

### LINKED ISSUE #424: PostgreSQL as Database Provider
Hello, how is support for the PostgreSQL? There is good support with Npgsql, and even with EF Core.

### PR DESCRIPTION
**Pull request by junderhill**
Added support for PostgreSQL identity including seeding admin user based on the existing class libraries for SQLite, SQL Server etc.

Resolves #424

Just one thing to note, when I tried to use this in the example MVC project within the repo I wasn't able to however when I tried using default SQLite configuration I had the same errors. It didn't seem to run the identity migrations and there were issues relating to it trying to execute multiple 'SaveChangesAsync' calls to the context before another had finished during the Seed() method. I haven't gotten to the bottom of this yet however I have tested the PostgreSQL library in one of my projects that is currently SQLite (hoping to migrate to PostgreSQL) and it worked flawlessly. The issues I saw may have been related to my dev environment though.

### CODE REVIEW

**Comment by junderhill** [comment]
I'm not sure why two of the checks have failed, the appveyor build seems to be something unrelated and code quality one is based on the use of the partial keyword on the IntialCreate migration which is auto generated across two files, `20190513131618_InitialCreate.cs` and `20190513131618_InitialCreate.Designer.cs`. If anyone has any critisms though I'm happy to receive any pointers

**Comment by tidyui** [comment]
The `AppVeyor` job is not setup properly for feature branches, there's a problem with the code coverage analysis. I have just concern regarding this and that is maintenance. We run tests on every version for `SQL Server` and `SQLite`, we don't have resources or environments setup for maintaining `PostgreSQL`, just like the core team doesn't maintain the `MySql` implementation.

I'd be happy to merge this, but I would need a commitment that someone makes sure this project stays up to date if we were to add features to the Identity package in future versions.

We've also talked about maybe creating separate repositories for different database implementations, or just creating a **contrib** repository where the core team is not the primary people maintaining it. What solution do you think would be best?

Best regards

**Comment by junderhill** [comment]
@tidyui Seperate repositories or a seperate contrib repo would definietly make sense. I think that would be a good idea going forward. In terms of preference, I think at this stage seperate repositories for each db implementation would be my choice.

I'd be happy to continue to maintain the `PostgreSQL` library as it's a necessity for some projects I'm working on.

**Comment by tidyui** [comment]
I'll go ahead and merge this PR and then we can figure how we want to maintain the code!

**Comment by niem94** [comment]
@tidyui will this be a part of v7, or do you plan to make a minor release in between? :-)

**Comment by junderhill** [comment]
@niem94 You can install this as an additional package through NuGet. 

```
dotnet add package Piranha.AspNetCore.Identity.PostgreSQL --version 6.1.0
```

**Comment by niem94** [comment]
@junderhill Awesome! Thanks!

**Comment by niem94** [comment]
@junderhill I just tested it on my environments, and it works flawlessly with heroku 👍

**Comment by junderhill** [comment]
@niem94 that’s great to here, I’m using it in a new clients project at the moment and seems to be working well 👍

**Pull request merged**
