### PR TITLE
Code styling, naming and refactoring 

### PR DESCRIPTION
**Pull request by alirizaadiyahsi**
I did some change to improve code quality, because I believe If the code quality is high and conforms to the standards, it will provide more contribution. Of course, I can not claim to be the best, but I followed the instructions below,

[Replace Nested Conditional with Guard Clauses](https://refactoring.guru/replace-nested-conditional-with-guard-clauses)
[C# Coding Standards and Naming Conventions](http://www.dofactory.com/reference/csharp-coding-standards)
[Using C# 7.0 features](https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/)

I know there are a lot of changes :) but, I did end-user tests. And also unit tests have been run succesfully.
image

### CODE REVIEW

**Comment by tidyui** [comment]
I **truly** appreciate your effort, but I will **not** accept your Pull Request. Some of your fixes, like removing unused namespaces would've been a nice contribution as these have slipped by since Visual Studio Code just doesn't highlight it as clearly as Visual Studio does.

The others, like certain naming conventions, putting opening braces on a new line and so on are **PURELY BY OPINION** and has absolutely nothing to do with code quality. This is why all of these things actually have settings in Visual Studio > Options where you can toggle how you want to format your code.

I am fully aware that certain code quality/review tools (like ReSharper) has a pretty strong opinion on **how they think** code should be formatted, but again, it's **only an opinion**.

Again, I truly appreciate your effort, but in the future when contributing to an open source project, don't reformat code that people have worked on for years, it's insulting. Instead try to follow the same standard when writing code for that project and the owners will be much happier.

I hope to see more pull requests in the future!

Best regards!

**Comment by alirizaadiyahsi** [comment]
> The others, like certain naming conventions, putting opening braces on a new line and so on are PURELY BY OPINION

true, but almost all popular open source .net projects on github following the same instuctions (ex: certain naming conventions, putting opening braces on a new line and so on)

Of course you know them:
https://github.com/aspnet
https://github.com/dotnet-architecture
https://github.com/Microsoft

> don't reformat code that people have worked on for years

This means "you should follow the legacy/private instructions or standards"

> Instead try to follow the same standard when writing code for that project and the owners will be much happier.

You are right, if you are doing open source development just for the happiness of those who think like you and yourself  :)

I think, if you expect support from people, then you should follow popular development standards like this PR. I would have expected you to send change request, but again, if your purpose is happiness, it is ok.

> it's insulting.

I don't agree. If you developing an open source project, you should not think like that.

Note: if I speak rude, it is my poor English, sorry for that :)

**Comment by tidyui** [comment]
No you're not rude at all! And it's really hard not to sound agitated or offensive in writing, that's why I also tried to be very clear that I wasn't angry either in my comment :)

> Of course you know them:
> https://github.com/aspnet
> https://github.com/dotnet-architecture
> https://github.com/Microsoft

The reason for the three accounts you referenced having the same code convention is that they are all by **Microsoft**, which have a very clear corporate code style convention.

> This means "you should follow the legacy/private instructions or standards"

Yes

> You are right, if you are doing open source development just for the happiness of those who think like you and yourself :)
> 
> I think, if you expect support from people, then you should follow popular development standards like this PR. 

Well I agree with nothing you wrote. Where you put your opening braces has nothing to do with the intention of your open source contributions, just like it has nothing to do with the quality of your code. Thinking like this is fixating on stuff that is not relevant, nor the primary objective. It's like writing a book and worrying about which pen you're going to use instead of what you're actually going to write with it. Like I wrote before, many of the things you did in your PR I would have gladly accepted, for example:

* Removing unused namespaces
* Updating code syntax to more modern C# 7.0 alternatives

> I would have expected you to send change request, but again, if your purpose is happiness, it is ok.

I would have loved this, but I just thought there were too many changes in the PR that it wouldn't be feasible. I can reopen the PR if you think it is doable, but since I assumed you used a refactoring tool (like ReSharper) for most of the changes I just figured it would be faster to make a new one :)

Personally I've worked professionally as a software developer for over eighteen years, and during that time on a number of large companies. On all of these large companies there has been **at least one** code convention war, and **none** of these wars ever resulted in anything good or useful.

What I meant by **insulting** was that when you send a PR where you change an entire code base based on an opinion, it's kind of like saying that your opinion is the only opinion and you don't care about other people's opinions. Also, it's **impossible** for someone to accept such a PR. As there are so many changes that it's impossible to review, accepting it means blindly trusting the name of the PR. The person accepting it has no idea what has happened, which makes life very hard for someone who has to handle support.

**Last but not least!** I'm going to open an issue labeled as `question` regarding the code convention of the repo. If there were to be an overwhelming desire to reformat the code base to Microsoft standard then I could consider doing it myself as I would then at lest know exactly what's in that moster commit :)

Regards

**Comment by alirizaadiyahsi** [comment]
Code convention is not about quality, you are right. 

Following are about quality:

- Replace Nested Conditional with Guard Clauses (there are a lot of them in code)
- Removing unused namespaces (these are performance penalties)
- Updating code syntax to more modern C# 7.0 alternatives
- if-statement best practices (these are already known that which is the best, [link1](https://stackoverflow.com/questions/2125066/is-it-bad-practice-to-use-an-if-statement-without-brackets), [link2](https://softwareengineering.stackexchange.com/questions/2715/should-curly-braces-appear-on-their-own-line) )

##### About contribution:

May be I can't explain what I meant. Most of .net developers are using VS default code convention(naming suggestion) and styling. For example: When I open your project and use some shortcut to tidy up the code(this is a habit as you know), then code will change. So I should change my IDE standards or I don't use most of shortcut. Not just microsoft use these standards and default settings of IDEs, there are a lot of popular projects.

> Also, it's impossible for someone to accept such a PR. As there are so many changes that it's impossible to review, accepting it means blindly trusting the name of the PR. The person accepting it has no idea what has happened, which makes life very hard for someone who has to handle support.

You are right. My fault, I should have open issues for every change or open seperate PRs. 

> I just figured it would be faster to make a new one :)

Yes :)

**Pull request closed without merging**
