### PR TITLE
Version/v8.4

### PR DESCRIPTION
**Pull request by axunonb**
Upgrade to TinyMCE as pointed out in https://github.com/PiranhaCMS/piranha.core/issues/1379

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/PiranhaCMS/piranha.core?pullRequest=1426) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/PiranhaCMS/piranha.core?pullRequest=1426) before we can accept your contribution.<br/><br/>:x: axunonb [sign now](https://cla.dotnetfoundation.org/PiranhaCMS/piranha.core?pullRequest=1426)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/PiranhaCMS/piranha.core?pullRequest=1426) it.</sub>

**Comment by tidyui** [comment]
Hi there! As you can see this PR has a massive amount of conflicting files that should not have been changed in the PR. It also contains two commits that already exists in the `version/v8.4` branch causing even more confusion. Can you update the PR or create a new one with your changes on an up-to-date version of the `v8.4` branch.

Best regards

**Comment by filipjansson** [comment]
Shouldn´t this PR also be selected to merge into the `version/v8.4` branch instead of `master`?

**Comment by axunonb** [comment]
> 
> 
> Shouldn´t this PR also be selected to merge into the `version/v8.4` branch instead of `master`?

Yes, it should. The conflicts the PR causes are weired, because I was shure to check-out the latest version of the repo a few minutes ago.

**Comment by tidyui** [comment]
Then the error is probably due to you targeting it accidentally to master. Try to close it and make a new PR for v8.4

**Pull request closed without merging**
