### PR TITLE
Piranha.EF.Tests PageTypeRepository and Piranha.Manager.Tests PageTypeController

### PR DESCRIPTION
**Pull request by TheWolfA2**
### Apologies
I apologize in advance, I realize now that I goofed up how I should be doing and handling these unit testing Pull Requests.  From now on, I will do these in much smaller sizes with each test project having its own branches from which I will make a pull request. If you have any advice on how better to structure my repo and create pull requests feel free to say something! This is pretty much my first time forking a repo and contributing to an open-source project!

### Piranha.EF.Tests
* Created an `internal interface Piranha.EF.IDb` for use in mocking in the unit tests
    * Internal classes are only exposed to `Piranha.EF.Tests` to allow for the `Piranha.EF.Db` implementation class to remain as a sealed class as discussed in #15 
* Introduced `Moq` for mocking interfaces in the unit tests
* Implemented unit tests for all public `Piranha.EF.Repositories.PageTypeRepository` methods excluding `Save()`

### Piranha.Manager.Tests
* Created an abstract base class to use for unit testing controllers
* `Piranha.Areas.Manager.Controllers.BlockTypeController` unit tests complete
* `Piranha.Areas.Manager.Controller.PageController` unit tests complete
    * `PageController.Save()`, `PageController.UnPublish()`, and `PageController.Publish()` have some failing unit tests as documented [here](https://github.com/TheWolfA2/piranha.core/issues/1) and [here](https://github.com/TheWolfA2/piranha.core/issues/3)

### CODE REVIEW

**Comment by tidyui** [comment]
No problem! This article describes a good workflow:

https://guides.github.com/introduction/flow/

Basically, don't code in master. Create a feature branch, send a pull request from that branch to the remote master, wait for the merge then sync your own master against the remote master. Then just repeat the procedure :)

I'll take a look at and merge the PR as soon as possible!

Regards

**Comment by TheWolfA2** [comment]
Appreciate the link! That's definitely helpful in understanding how to manage pull requests and branching from now on (as well as better management of my own projects).  I'll be sure to open more incremental pull requests from branches that are specifically focused on the individual modules

**Comment by tidyui** [comment]
I've merged the PR & pushed my changes & work in progress. Make sure you sync your master branch and then create new feature branches from there. Just a question on the class `Extend.PostType` that you've added, I wasn't planning on incorporating post types in the first version, and there doesn't seem to be any references to it at this point so I might remove it for now!

**Comment by TheWolfA2** [comment]
I actually am not exactly sure why I created the `Extend.PostType` class. I think it had something to do with needing the `PostListModel` for a controller/test but then I realized it wasn't needed or being used much at this point? But then I stopped working on it because I knew I didn't know the architecure of the `Extend.PostType`. You're welcome to delete it!

**Pull request merged**
