### PR TITLE
AppVeyor Unit Testing Setup

### PR DESCRIPTION
**Pull request by TheWolfA2**
## Unit Test Changes
Started refactoring unit tests to follow a new scheme for naming test methods. Instead of using PascalCase on the entire test name, I've used a combination of PascalCase and underscores to help highlight what method is being tested, and separate it from the actual description of the tests
```
public class UnitTestClass [: UnitTestsClassBase] // if one exists
{
    [Fact]
    public void MethodName_TestDescription() {
        // ...
    }
}
```

## AppVeyor Setup Instructions
* Modify build settings
    * Enter the following command into the *Before build script* setting
        * This may be optional, I was having issues with the initial AppVeyor build and this seemed to solve it
    ```
    dotnet restore
    ```
        

    * Enter the following command into the *After build script*
    ```
    cd test
    ````
* Modify Tests settings
    * Enter the following command into *Tests Script*
    ```
    .\RunTests.ps1
    ```
    * AppVeyor was having trouble properly discovering and running tests, so I created a script to run
    * This script will iterate over all project paths in the test/core/, test/data/, test/env/, and test/examples/ folders which match the string `*.Tests` and run each test
        * If at least 1 package fails, the script will use an `exit 1` statement at the end to ensure the AppVeyor build fails

### Non-deterministic test results
As discussed in #42 , it was discovered that `Piranha.App` is not thread safe, especially in the `PageControllerUnitTests` tests. Suggestions for possible fixes have been listed there but I will repeat them here as well:

* Remove the `Piranha.App` cache entirely, since this creates a race condition, and performs, in my opinion, an unnecessary level of caching
    * Yes, this increases the number of DB hits when making pages, but I think the relative trade-off of hitting the DB as opposed to risking race conditions is a a worthwhile loss of performance
* Find a mechanism to isolate and enforce serialized unit test running
    * This has a major trade-off in that running unit tests will require a greater amount of time since all tests within a project can't overlap
* ~~Find a way to create an injectible `IApp` interface of some kind?~~
    * ~~This doesn't seem totally plausible, since the idea of `App` is to cache info, however this would still result in a global resource which the unit tests (and ultimately users) are competing for~~
* Implement a cache interface (such as `IApp`) and use an optimistic concurrency scheme similar to [EF Optimistic Concurrency](https://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/handling-concurrency-with-the-entity-framework-in-an-asp-net-mvc-application) to help reduce this issue in a production environment
    * Unfortunately, I don't believe this will solve the issue within unit tests, unless the interface is able to be injected into the lower levels during setup. This would allow for isolated `Mock<IApp>` objects for each test and prevent altering global state between concurrently running tests

### Unit tests script for non-Windows environments
As far as I am aware, Mac and Linux systems don't natively support PowerShell and are therefore unable to use `RunTests.ps1` for running all unit tests at once. I will work on a bash script that can be run in non-Windows environments, and then update the `~/.vscode/tasks.json` file so that it can use the `Run Tests` command in VSCode to run all tests.

### CODE REVIEW

**Comment by tidyui** [comment]
Great! I have some WIP locally and I'll have to merge manually and check the conflict but I'll sort it out as soon as possible!

**Comment by TheWolfA2** [comment]
I went ahead and fixed my BlobStorageSession ctor to be public (instead of internal), since that was causing the merge conflict. Figured it was a trivial fix that didn't require viewing

**Comment by tidyui** [comment]
I tried setting up the AppVeyor account according to your comments, but I get the following errors when executing the tests.

https://ci.appveyor.com/project/tidyui/piranha-core

Any ideas?

**Comment by TheWolfA2** [comment]
Some of the errors are to be expected as some of the projects don't have any actually binary being created since they don't have any classes to compile (such as Piranha.Core.Tests, and Piranha.AspNet.Tests). Since it's not creating a binary, it's failing the "Run" statement. I can make a PR that has the dummy tests again so that those projects aren't failing until some unit tests are actually written.

Pirana.Manager.Tests is failing due to the thread safety issue surrounding `App` that we had discussed in #42 Until that issue is fixed, it's unlikely the AppVeyor build will give a green status

Piranha.EF.Tests is totally my fault, I committed some changes that had new unit tests for the `CategoryRepository` but I hadn't finished writing them at that moment. They are done now though, so I will be sure to include those in the PR for the dummy tests

**Comment by tidyui** [comment]
Ok, I added some Dummy tests to fix some of the easy errors. Now when running locally, only the CategoryRepository test fails & some manager tests. I'll take a look at the threading issue and see what I can come up with, but it will be easier for me to debug if I know the tests are ok in the first place!

Regards

**Pull request merged**
