### PR TITLE
[WIP] Editor UX Changes for v7.0

### PR DESCRIPTION
**Pull request by i-love-code**
Hey there, just to start off, great work on v7.0. It's coming along really nicely.

I've been watching as it progresses and I've recently built a blog on the platform (ilovecode.io) and I've loved how easy it has been. With the introduction of v7.0 I saw some changes to editor UX that I was a little skeptical of, so I wanted to throw a PR your way and get your thoughts on some changes.

Changes:
1. Display content region selection in another form than dropdown

I think content regions are too important to hide behind a double-click action alike a dropdown. I took a quick first stab at this to see how it felt, and I liked it, but it would likely need to be finalized with tabs/buttongroup and styled a bit, but the general concept is there.

Also, I moved it outside of the "topnav" aka the floating panel. I think it makes sense to have administration related actions in the top bar and content regions be within the content area...

2. Separated draft page-actions from publish and administrative actions

befb7f962892c68613a926708e45afdf (1)

Drafts are great, but they're not everyone's preferred method of editing. Having had to explain content editing to many editors in the past, something that's glaringly obvious is when two steps are needed to perform a single-click action alike publish or save. 

In the same thread as not hiding content regions behind a double click dropdown menu, I think it makes a lot of sense to not hide publish vs. draft in a dropdown menu. I've separated the two, making draft management (save and revert) separate from the publish/unpublish/delete actions of editing.

Items that would need to be completed still, if you're open to the ideas:

1. Finalize UX and placement of the new content region tab selector
2. Finalize localizations of changed Save Draft/Edit Region translations

I would be happy to wrap ^ these items up better, but I wanted to see your feedback on the above first:

I look forward to hearing your thoughts!

### CODE REVIEW

**Comment by tidyui** [comment]
Hi there! Good ideas, we were just discussing the new publishing workflow this Friday and we will spin this around some more. Just to clarify (and complicate), publishing a new version is not necessary  a 2 step action, the hard part is how to describe it properly.

**Publish** is in fact **Save & Publish**, in other words, if you’ve updated a live page, clicking just publish will do the trick.

**Save** is in fact **Create working copy**, or when it has been created, **Save working copy**. 

We definitely have go through the entire UX for this a second time as we need this to be self explanatory.

Regarding the regions Filip has stylized you version a bit which we can share with you. I’m not a big fan of the buttons/tabs, we’ve used this since version 1.0 and it quickly gets cluttered and as not as functional for smaller layouts, but we’ll take a second look at it!

Best regards

**Comment by i-love-code** [comment]
Hey there,

Sorry I can see how that came off differently, the animated gif of me messing up and clicking "Save Draft" before publish probably just made it worse. I was referred to the two-step action of clicking the "Save" dropdown and then clicking "Publish" to instant-publish changes in the original version:

6c5a07033e0290dc282f906670c79e8b

versus the standalone publish button being an alternative to the draft workflow accessible without using the dropdown.

I'd love to see the stylized version Filip has of the region selection area. I think it can help make switching between regions much more fluid.

Chris

**Comment by i-love-code** [comment]
Also, one additional editor UX QoL change I wanted to submit: Allow for the creation of media folders while selecting assets during the page/post/site editing workflow.

I often forget to create the folder for a blog post prior to editing the page, and I have to either navigate away from the draft of content changes or have the media editor up in another window to create the folder.

**Comment by filipjansson** [comment]
We added tabs in the media view because the toggle button was so anonymous and didn't really explain it self for what is was for. So i did a quick test to display the regions as tab also in the same manner. 

region-tabs
region-tabs2
region-tabs3
region-tabs4

**Comment by i-love-code** [comment]
I like it!

I'm torn between which one I like more, hanging from the topbar or sitting atop the content tabs.

**Comment by tidyui** [comment]
Closed as suggestions have been incorporated into the master branch with modifications!

**Comment by i-love-code** [comment]
Thank you @tidyui and @filipjansson! I just checked it out, looks great!

Super glad this made it in.

**Pull request closed without merging**
