### PR TITLE
Base structure for unit tests

### PR DESCRIPTION
**Pull request by TheWolfA2**
Created the basic folder structure for unit testing piranha.core, including xUnit for unit testing for all applications. Still a dependency issue with `Piranha.Azure` at this point so this will need to be looked into.

Focused on a simple framework for unit testing the `Piranha.Manager` controllers, with a few sample unit tests for the controllers. Still need a better understanding of how the controllers are designed before delving in further with more tests

### CODE REVIEW

**Comment by tidyui** [comment]
Just a couple of comments on the pull request!

## Formatting

Try not to reformat the entire code files when you update something. The entire code base uses starting braces on the same line for everything but **namespaces** and **classes**, for example:

    public void Method() {
      if (true) {
        // Do something
      }
    }

## Members

I don't use `_memberName` for class members. Adding the now on certain places will make the code structure diversed. 

## Copyright/Legal header

If you add a new file into the repo, add the legal header at the top of the file and your name as the contributor, in your case that would be:

    /*
     * Copyright (c) 2016 Billy Wolfington
     *
     * This software may be modified and distributed under the terms
     * of the MIT license.  See the LICENSE file for details.
     * 
     * https://github.com/piranhacms/piranha.core
     * 
     */

That's it! I'll modify the stuff in the current pull request to match the above!

Regards

**Comment by TheWolfA2** [comment]
Got it! I'll make sure to use `camelCase` without underscores for members, and I'll do a better job of including those legal licenses (first time contributing to open source, completely forgot about that).

My understanding of the formatting is classes and namespaces will keep opening curlies on separate lines, but all other opening curlies (methods, properties, conditionals, loops, etc.) should place them on the same line. I'll go back and try to make the fixes to better follow style guidelines!

**Comment by tidyui** [comment]
That's no problem!

**Comment by TheWolfA2** [comment]
What are the naming convention for `const` variables? I'm used to seeing and using `ALL_CAPS`, but it looks like the only const I can see in the project is `PascalCase`. It's the only one I've found, so I would like to argue `ALL_CAPS` should be the standard, because it makes it clear the values are a special case/value

**Comment by tidyui** [comment]
Yes I normally use ALL_CAPS as well so that's fine! And I wasn't even aware there were any const members in the repo, where did you find it :)

If I made it in camel case it's probably a temp fix for what is supposed to be a public member or property!

**Comment by TheWolfA2** [comment]
`Piranha.EF.Repositories.ArchiveRepository.ArchivePageSize`, however it has a note that it is supposed to be configurable so that's probably why :)

**Comment by tidyui** [comment]
A couple of pointers (for future reference) that I just noticed regarding the PR:

## AreaAttribute on base class
When positioned on the base class the view engines misses it when determining the view location and doesn't check the view folders of the area.

## Case sensitive area name
When working with embedded views the area name is case sensitive. This is most likely as embeded view becomes a compiled view with a generated namespace. This means it has to be `[Area("Manager")].

## SqlServer reference in Piranha.Manager
I removed the reference and changed the test setup to use Sqlite which is the default provider included in Piranha.EF.

## Launch
I changed the default launch command to the example blog as this is the test project and also includes the embedded manager.

**Comment by TheWolfA2** [comment]
## `AreaAttribute` on base class
Not sure what you mean when you say that the view engine misses the area attribute. I have a sample MVC app with an area that uses inheritance of the `AreaAttribute` and it renders the correct view from the Sample/Views/Home folder. I also ran the Blog example project with the area attribute on the `ManagerAreaControllerBase` and I received the correct views within the manager area. Is there something I'm missing or a specific example you can point me to of how it fails?

## Case sensitive area name
Whoops! Sorry about that, I'll be sure to watch out for that

## SqlServer reference in Piranha.Manager
Excellent! Makes development at least a bit easier :)

**Comment by tidyui** [comment]
Regarding the attributes I found it quite strange as well. But all views that inherited the base class didn't find their views (embedded views) and the error output showed that it didn't scan the area folder.

On the other hand I changed the ManagerAreaControllerBase to `abstract`, maybe this issue is just that abstract classes are skipped when scanning for Route/Area attributes?

**Comment by TheWolfA2** [comment]
Nope, mine is an abstract as well and there was still no issue. Maybe it was an issue in spelling of manager in some way? I'd suggest running it locally because documentation and my own personal testing show that it works. I can also commit my work to my repo and you can check mine out and see if there is some type of extra config in place I'm not seeing?

**Comment by tidyui** [comment]
That's no problem, I can try to move the attribute back to the base class now that the spelling is resolved, maybe that was the issue all along :)

**Pull request merged**
