### PR TITLE
Features/issue512/audio content

### PR DESCRIPTION
**Pull request by 5w33n**
Hey @tidyui ,

As promised - first PR so feel free to roast me :-)

Points of note:

- It largely copies from the video control, like right down to copyright notice in the case of new files, and level of unit-testing included
- Went with **fa-headphones** for the icon but don't have any strong preference if you want to change it
- Added DisplayTemplate to the Examples/MvcWeb project, after reading a comment on issues that a similar Video display template will be added to there soon. Did not try bake a concrete example of an audio control into the example site though...
- For the MediaTypeList, went with somewhat awkward "Audios" rather than "Audio", just to keep it consistently plural across the MediaTypeLists.
- MIME type is "audio/mpeg" rather than "audio/mp3" ... based on [this RFC ](https://tools.ietf.org/html/rfc3003)

I think that's it - all feedback welcome...

Cheers,

Stephen

### CODE REVIEW

**Comment by tidyui** [comment]
@filipjansson can you take a look at this.

**Comment by tidyui** [comment]
I’m currently away from my computer @5w33n. Either @filipjansson has time to look at this  or I’ll do it when I get back!

Regards

**Comment by 5w33n** [comment]
Hey,

I've found a couple more things that I need to include in this PR, but also one issue (which could be pre-existing, I've not had a chance to check) that I need to investigate further so feel free to hold off on reviewing this. 

Thanks,

Stephen

**Comment by 5w33n** [comment]
image

Okay, that should do it @filipjansson and/or @tidyui  - apologies for the delay there, I wanted to get the above looking correct.

One other thing that might be totally normal, is that I've not included updates to style.css and script.css (or minimized counterparts) because my versions of those contained significantly more changes than I made to the contributing files. To keep my PR 'pure' I've left the regeneration of those up to you or the CI build...

**Comment by filipjansson** [comment]
Hey!

Thank you for your contribution, this look good and works great.

BR
Filip

**Comment by 5w33n** [comment]
Very welcome - keep up the great work!

**Pull request merged**
