### PR TITLE
Implement GetAll<T> method in IArchiveRepository and ArchiveRepository.

### PR DESCRIPTION
**Pull request by Talagozis**
Hello again,

I would be grateful to have this GetAll method in the ArchiveRepository. This method can return all the archives of the blog site. For example, it could allow anyone to display all the different archives of his blog site in a single page.

I hope these changes do fit in the concept of the project and they can make it in the 5.2.0 version, too.

### CODE REVIEW

**Comment by tidyui** [comment]
Hi there! I didn't have time to look at and merge this for the `5.2` release. I'll look into it and maybe we can release in a service release.

Best regards

**Comment by tidyui** [comment]
I'd like to know a bit more what your intended use case for this method is. As I can see from the code it simply returns **all** Archive Pages implementing the specified Page Type from **all** Sites (as there's no `SiteId` parameter) and each of their archives.

Since categories and tags are in fact **unique** per archive, using the category or archive filters will in fact empty all archives in the result except one of them.

I can see the value of having a method returning a merged Archive for several Archive Pages if you would for example want to display the X latest posts out of all posts in an archive. This could for example look like:

    PostArchive GetArchives(Guid? siteId = null, int page = 1, int year = null, int? month = null, 
        int? pageSize = null)

Fetching a merged archive would also allow for paging and calendar based filtering on the joined archive.

Best regards

**Comment by Talagozis** [comment]
Thank you for your feedback. I can see that you are right on this and neither categories or tags fit in this method of the repository. I 've changed the parameters of the GetAll<T> to remove unnecessary ones and added siteId. It is pretty much like you mention above.

I would like to have a page where I can list all the archive pages that my site include, and why not, the top posts of each of them or something similar.

Thank you for your time.

**Comment by tidyui** [comment]
Sorry for not getting back to you on this one. We will make a complete overhaul of the archive repository to provide better support for things like this, for now you can just do the following code, and if you're using **full** cache it won't be a performance hit as the post models will be cached meaning that the call to `GetById` will just access the database the first time.

The following example gets the 10 latest posts from all archives in all sites.

    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    using Piranha;
    using Piranha.Models;

    public IList<PostBase> GetLatestPosts(IApi api, IDb db)
    {
        var posts = db.Posts
            .AsNoTracking()
            .OrderByDescending(p => p.Published)
            .Take(10)
            .Select(p => p.Id)
            .ToList();

        var models = new List<PostBase>();
        foreach (var post in posts)
        {
            models.Add(api.Posts.GetById(post));
        }
        return models;
    }

**Pull request closed without merging**
