### PR TITLE
Update and consolidate NuGet packages

### PR DESCRIPTION
**Pull request by rjcarneiro**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/PiranhaCMS/piranha.core?pullRequest=1875) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/PiranhaCMS/piranha.core?pullRequest=1875) before we can accept your contribution.<br/><br/>:x: rjcarneiro [sign now](https://cla.dotnetfoundation.org/PiranhaCMS/piranha.core?pullRequest=1875)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/PiranhaCMS/piranha.core?pullRequest=1875) it.</sub>

**Comment by rjcarneiro** [comment]
For some reason, there are changes on the `Piranha.Manager` `/assets/dist/` folder.

**Comment by tidyui** [comment]
We usually update dependencies closer to release, and we also can't accept the PR as there are modification in the compiled js-files that shouldn't be a part of the PR.

Best regards

**Comment by rjcarneiro** [comment]
Okay, thanks for the feedback!

**Pull request closed without merging**
