### PR TITLE
[WIP] Adding MySQL Database Provider for Identity 

### PR DESCRIPTION
**Pull request by aatmmr**
### Purpose

I have added a new Project `Piranha.AspNetCore.Identity.MySQL` offering MySQL as database provider for Piranhas Identity (see #269). Piranha can be used out of the box with MySQL as database provider for the content itself (see [example Repo](https://github.com/aatmmr/piranha.core)) but not for Piranhas Identity.

### Dependencies

It uses the package [`Pomelo.EntityFrameworkCore.MySql (v2.0.1)`](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) which is searching for new contributors so there might be a risk of dropping support in future, however, it is the only MySQL provider for EF Core that seems to work and there is nevertheless still some work going on for a new version (2.1).

### Current Issue - Help or Hints Appreciated

I struggle with the migration and I do not know why. Here's what I did:

- MySQL Server is installed and running (macOS Sierra)
- Using VS Code
- Added `Piranha.AspNetCore.Identity.MySQL` to `CoreWeb` project and wired everything in `Startup.cs`.
- Navigated to `Piranha.AspNetCore.Identity.MySQL` with Terminal
- Typed and run command:

  ```
  dotnet ef migrations add InitialCreate --startup-project ../../examples/CoreWeb/CoreWeb.csproj --context IdentityMySQLDb -v
  ```

That's where I run into the error:

  `Table piranha.piranha_roles does not exist.` 

The error is reasonable as the table / scheme does not exist but I just want to create the migration, not the database itself. Am I missing something?

### CODE REVIEW

**Comment by tidyui** [comment]
I think the problem lies here:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore.Identity/Db.cs#L58

Problem is probably that it creates the DbContext **before** trying to create the migration, but the constructor fails in the Seed. To verify, simply comment out the call to `Seed()` and then run `dotnet ef migrations add` again!

Let me know if it works!

**Comment by aatmmr** [comment]
Aweful 😄 That worked like a charm and added the migrations as wanted. Thanks for the quick reply!

**Comment by tidyui** [comment]
Great! One last question. I personally don't use MySql ever, nor do I have any MySql databases to test the provider on, or to test it before each release. This is a bit of a hassle as we're a rather small core team and we want to be able to provide good support and keep all of the code up to date.

How would you feel if we'd move this project to a new repo, something like `piranha.core.mysql` and I'd make you a core contributor for that. That is if you'd have the time to answer questions and check compatibility when new versions of the MySql provider is released.

Regards

**Comment by aatmmr** [comment]
MySQL seems to be the preferred database that smaller hosting providers use which was the reason I looked into the use of MySQL with Piranha as I wanted to use the CMS. 

I understand your hassle, so yes, we can move it to another repo.I suppose I'll provide it as nugget package which depends on `piranha.core` and and try to keep up to date with the core releases and check of compatibility. Is that roughly the idea?

**Comment by tidyui** [comment]
Either you handle the NuGet packages or we can handle it together with the rest of the packages. My idea was that we create a separate repository here under the PiranhaCMS account for MySql, and then I include you in the Piranha CMS organization and give you Admin rights to the repository! Then we can also release it on NuGet with a name like `Piranha.AspNetCore.Identity.MySql`. So I will definitely help out as well, it would just be good having someone onboard that knows MySql :)

**Comment by aatmmr** [comment]
That sounds all good to me :)  I have to admit that I am not an MySQL expert but I will collect experience and will stay up to date!

**Comment by aatmmr** [comment]
Pomelo Foundation is about to release a new version of their MySQL package for EF Core at 27/06/2018 - Version 2.1.0 which goes along with .NET 2.1.0. I would update the new package as soon as it is available.

**Comment by tidyui** [comment]
We can wait for the Pomelo package to be released before shipping `5.1`. There's still a bit of work left to be done on the remaining block feature issues!

**Comment by tidyui** [comment]
I'm wrapping up `beta1` for `5.1`. Have you had time to investigate if Pomelo have released the .NET 2.1.0 version on Nuget?

**Comment by aatmmr** [comment]
Funny you asked - the package version 2.1.1 was published just before you asked 😊 I try to check if it workes asap.

**Pull request merged**
