### PR TITLE
Version 4.4: Added checkboxfield

### PR DESCRIPTION
**Pull request by wiruzman**
For #230

### CODE REVIEW

**Comment by tidyui** [comment]
It looks like you’ve renamed the StringField serializer to your CheckBox serializer which will break the old fields!

**Comment by wiruzman** [comment]
I saw it and corrected :/

**Comment by tidyui** [comment]
No problems :) A PR is always better than NO PR!!! Keep up the good work!

**Comment by wiruzman** [comment]
Can you see why AppVeyor is breaking?

**Comment by tidyui** [comment]
Yes it looks that way, I’ll see what I can do in AppVeyor to not send reports to coveralls from PR’s

**Comment by tidyui** [comment]
Looks good! Maybe some tests for conversions and serialization! Look here for reference:

https://github.com/PiranhaCMS/piranha.core/blob/master/test/Piranha.Tests/Fields.cs
https://github.com/PiranhaCMS/piranha.core/blob/master/test/Piranha.Tests/Serializers.cs

**Comment by wiruzman** [comment]
will do

**Pull request merged**
