### PR TITLE
ArchivePage as a Child Page Advance Routing

### PR DESCRIPTION
**Pull request by gyretech**
My attempt to resolve an issue #699 where if you place an ArchivePage as a child of a Page routing would not work.

### CODE REVIEW

**Comment by tidyui** [comment]
If I remember our previous discussion I also guess the middleware needs to ordered differently? The current order is this:

    .UseMiddleware<Piranha.AspNetCore.ApplicationMiddleware>()
    .UseMiddleware<Piranha.AspNetCore.AliasMiddleware>()
    .UseMiddleware<Piranha.AspNetCore.PageMiddleware>()
    .UseMiddleware<Piranha.AspNetCore.PostMiddleware>()
    .UseMiddleware<Piranha.AspNetCore.ArchiveMiddleware>()
    .UseMiddleware<Piranha.AspNetCore.StartPageMiddleware>()
    .UseMiddleware<Piranha.AspNetCore.SitemapMiddleware>();

But I assume that **post** and **archive** now needs to be put before **page** for the routing to work?

**Comment by gyretech** [comment]
Yes, I am using this order:


.UseMiddleware<Piranha.AspNetCore.ApplicationMiddleware>()

.UseMiddleware<Piranha.AspNetCore.AliasMiddleware>()

.UseMiddleware<Piranha.AspNetCore.PostMiddleware>()

.UseMiddleware<Piranha.AspNetCore.ArchiveMiddleware>()

.UseMiddleware<Piranha.AspNetCore.PageMiddleware>()

.UseMiddleware<Piranha.AspNetCore.StartPageMiddleware>()

.UseMiddleware<Piranha.AspNetCore.SitemapMiddleware>();

**Comment by tidyui** [comment]
Great! I might save this PR a little while and look at it for `7.1`. The reason is that if I'm not mistaken this change would instead make it impossible to add a regular page below an archive. To resolve this we would have to resolve **all** pages & posts in the same middleware to ensure that it is done correctly instead of splitting it into several passes. This would probably also increase performance just a little bit in certain scenarios.

**Comment by gyretech** [comment]
I was thinking the same thing.

- Keshwar

________________________________

**Comment by tidyui** [comment]
Hi there! We have solved this in a different way with the new integrated middleware component in version `8.0`. https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/IntegratedMiddleware.cs

**Pull request closed without merging**
