### PR TITLE
added async repos

### PR DESCRIPTION
**Pull request by jackweldon**
Added async repositories into async folder, with interfaces

https://github.com/PiranhaCMS/piranha.core/issues/109

### CODE REVIEW

**Comment by tidyui** [comment]
Just a thought. There's a LOT of duplicated code here (since it's an async version of the original repositories). Do we need to have both sync & async repos? If that is the case we should probably move the common code (i.e. model transformations and so on) into repository base classes that both the sync & async version can use. This way only the actual database access is made async.

**Comment by tidyui** [comment]
And the issue you referenced (#109) was actually about making the `IStorageSession` interface async since most file providers & the Azure storage API is async for .NET core. Still it's a good idea to have async support for the data API's as well

**Comment by jackweldon** [comment]
Sorry, yes I agree it is alot of duplicated code but I wasn't confident enough to delete all the sync repos

**Comment by tidyui** [comment]
I will close this for now as Async API's are still in `Backlog` and hasn't been analyzed or scheduled
for implementation.

Thanks for your efforts nonetheless!

Regards

**Pull request closed without merging**
