### PR TITLE
Optimize deep cloning for value types

### PR DESCRIPTION
**Pull request by stefanolsen**
When the parameter passed into the method is a struct/value-type the method, then it will return the same value (no cloning), since only reference types need cloning.

### CODE REVIEW

**Comment by tidyui** [comment]
Thanks 👍

**Comment by stefanolsen** [comment]
Hi @tidyui.
I did some code profiling of the project (using MvcWeb). I found that deep cloning is slowing down the website, because of the JSON serialization and deserialization.
I have been testing out .Net cloning by making the Model classes implement the `ICloneable.Clone` method and use the built-in clone method. That should make it much faster. But it will probably not be API backwards compatible. So it might have to wait for version 7.
What do you think about that?

**Comment by tidyui** [comment]
Yes, the deep cloning was only added to ensure that **in memory** caches doesn't destroy the cached  version by mistake by returning a shared instance. We could also add the same logic as in the `DistributedCache` implementation where it uses `Binary Serialization` for all objects that is marked as `Serializable as this is the fastest way to clone an object. 

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Cache/DistributedCache.cs#L74

This solution would use binary serialization for all models **except** content models, **but** if we would mark all content base classes as `Serializable` the developer could get binary serialization for these models as well by marking Page & Post models with the attribute as well.

Then JSON would only be used as a fallback when caching objects that can't be serialized effectively.

**Comment by tidyui** [comment]
I'll add a feature branch for this so you can test it out!

**Comment by stefanolsen** [comment]
I am familiar with the rationale; I know other CMS'es that do the same.
My idea was to not do serialization at all for content models (which we control) and derived classes.
The thing with the `ICloneable` feature is that all content models would then have a `Clone` method, in which we can call ShallowClone on itself, or ShallowClone plus copying of nested lists etc. This will much faster than even binary serialization.
The method can fall back to serializing those non-content models that do not implement the `ICloneable` interface.
I will submit an example a little later.

**Comment by tidyui** [comment]
My only objection is that content models are made up of a lot of composable parts (fields, blocks) and so on. Relying on cloning would put a lot of responsibility on everyone that adds one of these components to implement their clone method 100% correctly. Serializing/deserializing eliminates these potential errors that can happen deep down for people using Piranha.

**Comment by tidyui** [comment]
https://github.com/PiranhaCMS/piranha.core/tree/features/binary-deepclone

**Comment by stefanolsen** [comment]
Great. I realize that my change (for ValueType) also applies to String. As they are immutable on their own they can be returned as-is, instead of copied. But if the string is a property value, it should be cloned with its object.

**Comment by stefanolsen** [comment]
Also, I saw this cloning method called "Expression Tree Cloning" that looks much faster than the `BinarySerializer`. Something I might test out.

**Comment by tidyui** [comment]
Also, if you want to get **maximum** performance you could just implement your own memory cache implementing `Piranha.Cache.ICache` that just skips the cloning, or we could add an option to our standard Cache if cloning should be applied or not. Like I mentioned it is really just a security precaution to minimize application errors if you expect that you are allowed to modify the objects returned from cache without altering the cache state.

**Comment by tidyui** [comment]
I've added an overload in the branch to initialize `SimpleCache` without cloning. For `MemoryCache` I probably need to create a derived class as it needs to be instantiated through the DI to get a reference to the underlying `AspNetCore` cache.

**Pull request merged**
