### PR TITLE
update from dotnet6 -> dotnet7

### PR DESCRIPTION
**Pull request by bbqchickenrobot**
updated sdk, nuget packages + workflow versions

### CODE REVIEW

**Comment by tidyui** [comment]
Hi there. We have previously updated the dependent packages (`AutoMapper`) that was required in order to run on .NET 7. We normally do not force upgrade Piranha to *non LTS* versions of .NET as these will go out of support fairly quickly, instead we make sure it can be run on those versions.

In other words, unless there is something stopping you from using the latest version of Piranha together with .NET 7 we won't accept this PR and instead wait for .NET 8 to update all package references.

Regards

**Comment by tidyui** [comment]
I'd be very much open to a PR targeting both .NET6 & .NET7, given this we could release a new minor on NuGet which has binaries for two runtimes.

**Comment by haarhoff-frs** [comment]
I'm having the same problem, can't really go back to .NET 6 because I make heavy use of C# 11 features.
I wouldn't mind having a look at multi-targeting, I'll just have to read up on the subject first 😅

**Comment by tidyui** [comment]
Resolved in #2005

**Pull request closed without merging**
